source "https://api.berkshelf.com"

metadata

cookbook "yum-epel"
cookbook "nginx", path: "../../site-cookbooks/nginx"
cookbook "php-env", path: "../../site-cookbooks/php-env"
cookbook "ruby-env", path: "../../site-cookbooks/ruby-env"
cookbook "nodejs", path: "../../site-cookbooks/nodejs"
cookbook "fluentd", path: "../../site-cookbooks/fluentd"
